expenseService:
  url: ${EXPENSE_SERVICE_URL}

spring:
  security:
    oauth2:
      client:
        registration:
          expense-client-authorization-code:
            provider: ${ OAUTH2_PROVIDER }
            client-id: ${ OAUTH2_CLIENT_ID }
            client-secret: ${ OAUTH2_CLIENT_SECRET }
            authorization-grant-type: ${ OAUTH2_AUTHORIZATION_GRANT_TYPE }
            redirect-uri: ${ OAUTH2_REDIRECT_URI }
            scope: ${ OAUTH2_SCOPE }
            client-name: ${ OAUTH2_CLIENT_NAME }
          provider:
            spring:
              issuer-uri: ${ OAUTH2_ISSUER_URI }

expenseServiceClientRegistrationId: ${ EXPENSE_SERVICE_CLIENT_REGISTRATION_ID }